services:
- type: web
  name: focus-api
  env: node
  plan: free
  buildCommand: npm install
  startCommand: node src/index.js
  envVars:
  - key: PORT
    value: 8080
  - key: DB_HOST
    sync: false        # añade en dashboard
  - key: DB_NAME
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_PORT
    value: "1433"
  - key: JWT_SECRET
    sync: false
